#!/usr/bin/env bash

if ! docker info >/dev/null 1>&1; then
  echo "Docker is not running. Please start Docker first."
  exit 0
fi

if [ ! -f .env ]; then
  PROJECT_PATH="$(
    cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit
    pwd -P
  )"
  PROJECT="$(basename "$PROJECT_PATH")"
  # Generate .env File
  echo 'PROJECT="'"${PROJECT}"'"' >.env
  echo 'PROJECT_PATH="'"${PROJECT_PATH}"'"' >>.env
  ./bin/setup
else
  . .env
  ./bin/start-container
  ./bin/control
fi
