version: "3.9"
networks:
  dev-network:
    driver: bridge
    name: dev-network
services:
  app:
    image: cth24/web-dev-php:${PHP_VERSION}
    container_name: ${PROJECT}-app
    restart: always
    working_dir: /var/www/
    extra_hosts:
      - "${PROJECT}.localhost:host-gateway"
    volumes:
      - ../src/:/var/www/
      - ../backup/:/opt/backup/
    networks:
      dev-network:
        aliases:
          - ${PROJECT}.localhost
  nginx:
    image: nginx:latest
    container_name: ${PROJECT}-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../src/:/var/www/
      - ./nginx:/etc/nginx/conf.d
    networks:
        - dev-network
    extra_hosts:
      - "${PROJECT}.localhost:host-gateway"
  db:
    image: mariadb:latest
    container_name: ${PROJECT}-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=4G --key_buffer_size=256M --max_connections=2000 --max_allowed_packet=16M --query_cache_type=ON --query_cache_limit=32M --query_cache_size=128M
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
      MYSQL_USER: website
      MYSQL_PASSWORD: website
    volumes:
      - ./storage:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - dev-network
  redis:
    image: redis:latest
    container_name: ${PROJECT}-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    networks:
      - dev-network